apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfastapiapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myfastapiapp
  template:
    metadata:
      labels:
        app: myfastapiapp
    spec:
      containers:
      - name: myfastapiapp
        image: quickstark/myfastapiapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: DD_AGENT_HOST
          value: "datadog-agent"
        - name: DD_AGENT_PORT
          value: "8126"
        - name: DD_ENV
          value: "dev"
        - name: DD_SERVICE
          value: "fastapi-app"
        - name: DD_VERSION
          value: "1.0"