version: '3.8'

services:
  fastapi-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Application Configuration
      - DD_SERVICE=${DD_SERVICE:-fastapi-app}
      - DD_ENV=${DD_ENV:-production}
      - DD_VERSION=${DD_VERSION:-1.0}
      
      # Database Configuration
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT:-5432}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      
      # External API Keys (from secrets)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATADOG_API_KEY=${DATADOG_API_KEY}
      - DATADOG_APP_KEY=${DATADOG_APP_KEY}
      # - SENDGRID_API_KEY=${SENDGRID_API_KEY}  # REMOVED: Trial ended, migrating to SES
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      
      # AWS Configuration (includes SES)
      - AMAZON_KEY_ID=${AMAZON_KEY_ID}
      - AMAZON_KEY_SECRET=${AMAZON_KEY_SECRET}
      - AMAZON_S3_BUCKET=${AMAZON_S3_BUCKET}
      - SES_REGION=${SES_REGION:-us-east-1}
      - SES_FROM_EMAIL=${SES_FROM_EMAIL:-dirk@quickstark.com}
      
      # MongoDB Configuration
      - MONGO_CONN=${MONGO_CONN}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PW=${MONGO_PW}
      
      # Application Specific
      - BUG_REPORT_EMAIL=${BUG_REPORT_EMAIL}
      
      # Container specific
      - PUID=1026
      - PGID=100
    
    env_file:
      - .env.production  # Production overrides
    
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 