version: '3'

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      
      # Web Server: JMX (existing) + APM (new)
      - SONAR_WEB_JAVAADDITIONALOPTS=
        -javaagent:/opt/datadog/dd-java-agent.jar
        -Ddd.service=sonarqube-web
        -Ddd.env=homelab
        -Ddd.trace.enabled=true
        -Ddd.profiling.enabled=true
        -Ddd.agent.host=172.17.0.1
        -Ddd.agent.port=8126
        -Ddd.logs.injection=true
        -Ddd.jdbc.analytics.enabled=true
        -Ddd.trace.db.client.split-by-instance=true
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=10443
        -Dcom.sun.management.jmxremote.rmi.port=10443
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Djava.rmi.server.hostname=sonarqube
      
      # Compute Engine: JMX (existing) + APM (new)
      - SONAR_CE_JAVAADDITIONALOPTS=
        -javaagent:/opt/datadog/dd-java-agent.jar
        -Ddd.service=sonarqube-compute
        -Ddd.env=homelab
        -Ddd.trace.enabled=true
        -Ddd.profiling.enabled=true
        -Ddd.agent.host=172.17.0.1
        -Ddd.agent.port=8126
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=10444
        -Dcom.sun.management.jmxremote.rmi.port=10444
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Djava.rmi.server.hostname=sonarqube
    
    ports:
      - "9010:9000"
      # Expose JMX ports for Datadog Agent on host
      - "10443:10443"
      - "10444:10444"
    
    volumes:
      - /docker/appdata/sonarqube/data:/opt/sonarqube/data
      - /docker/appdata/sonarqube/extensions:/opt/sonarqube/extensions
      - /docker/appdata/sonarqube/logs:/opt/sonarqube/logs
      # ADD THIS: Mount the APM tracer JAR (download it first with wget)
      - ./dd-java-agent.jar:/opt/datadog/dd-java-agent.jar:ro
    
    # If your Datadog Agent can't be reached at 172.17.0.1, uncomment this:
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    # Then change -Ddd.agent.host=172.17.0.1 to -Ddd.agent.host=host.docker.internal
    
    labels:
      # Your existing Datadog autodiscovery labels for JMX
      com.datadoghq.ad.check_names: '["sonarqube"]'
      com.datadoghq.ad.init_configs: '[{"is_jmx": true, "collect_default_metrics": true}]'
      com.datadoghq.ad.instances: |
        [
          {
            "host": "%%host%%",
            "port": 10443,
            "jmx_url": "service:jmx:rmi:///jndi/rmi://%%host%%:10443/jmxrmi",
            "name": "sonarqube_web",
            "tags": ["env:homelab", "service:sonarqube"]
          }
        ]
      # Datadog log collection
      com.datadoghq.ad.logs: |
        [
          {
            "source": "sonarqube",
            "service": "sonarqube",
            "log_processing_rules": [
              {
                "type": "multi_line",
                "pattern": "^\\d{4}\\.\\d{2}\\.\\d{2}",
                "name": "log_start_with_date"
              }
            ]
          }
        ]
    
    restart: unless-stopped
