apiVersion: apps/v1
kind: Deployment
metadata:
  name: images-api
  namespace: default
  labels:
    app: images-api
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: images-api
  template:
    metadata:
      labels:
        app: images-api
        version: "1.0"
      annotations:
        # Datadog APM annotations
        ad.datadoghq.com/images-api.logs: '[{"source": "fastapi", "service": "images-api"}]'
        ad.datadoghq.com/images-api.tags: '{"env": "dev", "service": "images-api", "version": "1.0"}'
    spec:
      containers:
      - name: images-api
        image: images-api:latest
        imagePullPolicy: Never  # Use local image from nerdctl
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_TRACE_AGENT_PORT
          value: "8126"
        - name: DD_ENV
          value: "dev"
        - name: DD_SERVICE
          value: "images-api"
        - name: DD_VERSION
          value: "1.0"
        - name: DD_LOGS_INJECTION
          value: "true"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: images-api-service
  namespace: default
  labels:
    app: images-api
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: images-api 