name: Datadog Software Composition Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run daily at 2 AM UTC to catch new vulnerabilities
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  software-composition-analysis:
    runs-on: ubuntu-latest
    name: Datadog SBOM Generation and Upload
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Match your Dockerfile Python version
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate and Upload SBOM to Datadog
      id: datadog-software-composition-analysis
      uses: DataDog/datadog-sca-github-action@main
      with:
        dd_api_key: ${{ secrets.DATADOG_API_KEY }}  # Using consistent secret name
        dd_app_key: ${{ secrets.DATADOG_APP_KEY }}
        dd_site: "datadoghq.com"
        dd_service: ${{ secrets.DD_SERVICE }}  # Add service tag for better tracking
        dd_env: ${{ secrets.DD_ENV }}  # Add environment tag
        
    - name: Upload SBOM as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: datadog-sbom-${{ github.sha }}
        path: |
          **/sbom.json
          **/sbom.xml
        retention-days: 30
        
    - name: Comment on PR with SCA results
      if: github.event_name == 'pull_request' && failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '⚠️ **Security Alert**: Datadog SCA found vulnerabilities in dependencies. Please review the [Datadog Security dashboard](https://app.datadoghq.com/security/appsec) for details.'
          })
