name: Datadog Security Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run daily at 2 AM UTC to catch new vulnerabilities
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  software-composition-analysis:
    runs-on: ubuntu-latest
    name: Datadog SBOM Generation and Upload
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Match your Dockerfile Python version
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Check imported libraries are secure and compliant
      id: datadog-software-composition-analysis
      uses: DataDog/datadog-sca-github-action@main
      with:
        dd_api_key: ${{ secrets.DD_API_KEY }}
        dd_app_key: ${{ secrets.DD_APP_KEY }}
        dd_site: "datadoghq.com"
        
    - name: Upload SBOM as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: datadog-sbom-${{ github.sha }}
        path: |
          **/sbom.json
          **/sbom.xml
        retention-days: 30
        
    - name: Comment on PR with SCA vulnerability results
      if: github.event_name == 'pull_request' && failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '⚠️ **Security Alert**: Datadog SCA found vulnerabilities in dependencies. Please review the [Datadog Security dashboard](https://app.datadoghq.com/security/appsec) for details.'
          })

  static-code-analysis:
    runs-on: ubuntu-latest
    name: Datadog Static Code Analysis
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Check code meets quality and security standards
      id: datadog-static-analysis
      uses: DataDog/datadog-static-analyzer-github-action@v1
      with:
        dd_api_key: ${{ secrets.DD_API_KEY }}
        dd_app_key: ${{ secrets.DD_APP_KEY }}
        dd_site: "datadoghq.com"
        secrets_enabled: false
        static_analysis_enabled: true
        cpu_count: 2
        
    - name: Upload Static Analysis results as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: datadog-static-analysis-${{ github.sha }}
        path: |
          **/static-analysis-results.json
          **/static-analysis-report.html
        retention-days: 30
        if-no-files-found: ignore
        
    - name: Comment on PR with Static Analysis results
      if: github.event_name == 'pull_request' && failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '⚠️ **Code Quality Alert**: Datadog Static Analysis found code quality or security issues. Please review the [Datadog Security dashboard](https://app.datadoghq.com/security/appsec) for details.'
          })
