name: Build and Deploy (Self-Hosted Runner) - Alternative SonarQube
on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Also allow manual trigger
    inputs:
      skip_tests:
        description: 'Skip tests'
        required: false
        default: false
        type: boolean
      skip_deploy:
        description: 'Skip deployment (build only)'
        required: false
        default: false
        type: boolean

jobs:
  build-and-deploy:
    # Use self-hosted runner
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for SonarQube analysis
      
      # Alternative: Run SonarQube scan in Docker container
      - name: SonarQube Scan (Docker)
        run: |
          if [ -n "${{ secrets.SONAR_TOKEN }}" ] && [ -n "${{ secrets.SONAR_HOST_URL }}" ]; then
            echo "Running SonarQube analysis in Docker container..."
            docker run \
              --rm \
              -e SONAR_HOST_URL="${{ secrets.SONAR_HOST_URL }}" \
              -e SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}" \
              -v "$(pwd):/usr/src" \
              sonarsource/sonar-scanner-cli \
              -Dsonar.projectKey=quickstark_demo-fastapi_6ba235ba-ff96-459d-8607-919121b2ad98 \
              -Dsonar.sources=main.py,src \
              -Dsonar.tests=tests \
              -Dsonar.language=py \
              -Dsonar.python.version=3.9,3.10,3.11,3.12 \
              -Dsonar.sourceEncoding=UTF-8 || echo "SonarQube scan failed - continuing anyway"
          else
            echo "SonarQube credentials not configured - skipping analysis"
          fi
      
      - name: System Information
        run: |
          echo "=== System Information ==="
          echo "Hostname: $(hostname)"
          echo "User: $(whoami)"
          echo "Working Directory: $(pwd)"
          echo "OS: $(uname -a)"
          echo "=========================="
      
      # Rest of your workflow continues here...
      # (Copy the rest from deploy-self-hosted.yaml)
